pipeline {
    agent any
    environment {
        IMAGE = "wireflex/jenkins"
    }
    stages {
        stage('Docker user(local and remote) and version') {
            steps {
                sh "echo $USER"
                sh 'docker version'
                sh "ssh ubuntu@3.127.221.103 'echo $USER'"
            }
        }
        stage('Delete workspace before build starts') {
            steps {
                echo 'Deleting workspace'
                deleteDir()
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'git@github.com:Wireflex/CI-CD.git'        
            }
        }
        stage('Test') {
            steps {
                dir('Jenkins/Nginx_html') {
                    sh "ls -la"
                    sh "pwd"
                }
            }
        }
        stage('Build docker image') {
            steps {
                dir('Jenkins/Nginx_html') {
                    sh 'docker build -t $IMAGE .'
                }
            }
        }
        stage('Push docker image to DockerHub') {
            steps {
                withDockerRegistry(credentialsId: 'dockerhub', url: 'https://index.docker.io/v1/') {
                    sh 'docker push $IMAGE'
                }
            }
        }
        stage('Delete docker image locally') {
            steps {
                sh 'docker rmi $IMAGE'
            }
        }
        stage('Create compose and transfer') {
            steps {
                sh '''
                cat << 'EOF' > docker-compose.yml
services:
  test:
    image: wireflex/jenkins
    ports:
      - '80:80'
    restart: unless-stopped
#EOF
            '''
                sh 'scp docker-compose.yml ubuntu@3.127.221.103:/home/ubuntu'
            }
        }
        stage('Deploy on remote') {
            steps {
                sh "ssh ubuntu@3.127.221.103 'cd ~ && docker compose down'"
                sh "ssh ubuntu@3.127.221.103 'cd ~ && docker rmi -f wireflex/jenkins || true'"
                sh "ssh ubuntu@3.127.221.103 'cd ~ && docker compose up -d'"
            }
        }
    }
}
