name: SelfHost_Actions

on:
  push:
    branches: 
    - main
    
jobs:

  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.1.0
        with:
          context: Jenkins/Nginx_html
          push: true
          tags: wireflex/actions
  
  deploy:
    runs-on: self-hosted
    needs: [build_and_push]
    steps:
          - name: Deploy at remote server
            run: |
              echo $HOST $HOSTNAME $HOME
              echo "
              services:
                test:
                image: wireflex/actions
                ports:
                  - '80:80'
                restart: unless-stopped" > docker-compose-actions.yml
              echo $HOST $HOSTNAME $HOME
              scp docker-compose-actions.yml ubuntu@3.127.221.103:/home/ubuntu
              ssh ubuntu@3.127.221.103  'docker compose -f docker-compose-actions.yml down'
              ssh ubuntu@3.127.221.103  'docker rmi -f wireflex/actions || true'
              ssh ubuntu@3.127.221.103  'docker compose -f docker-compose-actions.yml up -d'
